### ISSUE TITLE
amazing work

### ISSUE THREAD

**Issue by bararchy** [drhuffman12/ai4cr#15]
Just wanted to ping and say that this is an amazing work, a pure Crystal  ML lib is really needed, thanks for taking the time to port it.

Also, I would really love to see a RNN, CNN and maybe GNG or some other kind of unsupervised networks.

again, thanks :)

**Comment by drhuffman12** [comment]
@bararchy , Thanks, but I have to give most of the credit to the AI4R developers. Feel free to send links/suggestions or even fork/pr. For my next addition, I've been looking into RNN libraries; possibly extending the Backpropagation class.

**Comment by bararchy** [comment]
Hi @drhuffman12, don't know if you saw but we created an interesting project at https://github.com/NeuraLegion/shainet  

Take a look if you want, we would love feedback

**Comment by drhuffman12** [comment]
@bararchy , thanks for the link for shainet; looks interesting. I've been a bit busy with other stuff. I'll dig into it some more. I want to expand ai4cr and learn more about other AI options.
